### ISSUE TITLE
Use verbatim macro where possible

### ISSUE THREAD

**Issue by vladfaust** [onyxframework/http#28]
See https://github.com/crystal-lang/crystal/pull/6108

**Comment by vladfaust** [comment]
No need after params rewrite.

**Comment by sbrezinski70** [comment]
Please unsubscribe me from all this>>I don't know what youre doing..too bad I'm not up on your 'language here..but I don't want to be involved.  I don't need this aggravation--Leave me alone. please...Thank you

**Comment by vladfaust** [comment]
WTF?
