### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by s0kil** [onyxframework/http#36]
Are there any benchmarks for Prism?

**Comment by vladfaust** [comment]
Hi @DanielSokil, do you need benchmarks with other Crystal frameworks or with other languages?

**Comment by s0kil** [comment]
@vladfaust [Amber](https://github.com/amberframework/amber) would be great!

**Comment by vladfaust** [comment]
@DanielSokil ~~nah, newbies~~ The truth is that almost every Crystal framework is super fast. The difference is in amount of additional features. E.g. Prism has params extraction and typecasting and authentication module. They take time to proceed the request, but this time is so small you wouldn't even notice. This is beautiful - Crystal allows to choose projects based on their functionality, not on drastic speed differences like Rails vs Sinatra in Ruby :nerd_face: 

You can see overall web frameworks benchmarks @ https://github.com/the-benchmarker/web-frameworks. Beware of that Crystal results are outdated and slow speeds are results of performance issues in the latest versions. But you can see that all Crystal frameworks (excluding router.cr, which is not really a framework) have almost the same performance.

However, I will think about adding comparison.

**Comment by s0kil** [comment]
@vladfaust That's a good point, there won't be a huge performance difference.

**Comment by vladfaust** [comment]
Please see https://github.com/the-benchmarker/web-frameworks/issues/184#issuecomment-416588842

**Comment by s0kil** [comment]
Thanks! As someone already mentioned would be great to see http://realworld.io/.

**Comment by vladfaust** [comment]
@DanielSokil it's already here https://github.com/gothinkster/realworld/issues/223.

You see, nobody gives a F :man_shrugging:

**Comment by sandybrez** [comment]
Please unsubscribe me to all this..I believe someone hacked my phone and
has all my information. I don’t know what to do except take it to AT&T’s..

**Comment by s0kil** [comment]
@vladfaust Thanks for your effort.

**Comment by vladfaust** [comment]
The framework is currently `#1` among all Crystal projects according to the [**@the-benchmarker/web-frameworks**](https://github.com/the-benchmarker/web-frameworks/blob/fe0eb438826549371fb115ce5326110cef778341/README.md#full-table-1) 🎉
