### ISSUE TITLE
Error: Prism::Action is not a module, it's a struct

### ISSUE THREAD

**Issue by s0kil** [onyxframework/http#38]
## Running the basic example:
```crystal
require "prism"

struct KnockKnock
  include Prism::Action
  include Prism::Action::Params

  params do
    param :who, String
    param :times, Int32, validate: {max: 10}
  end

  def call
    params[:times].times do
      text("Knock-knock #{who}\n")
    end
  end
end

router = Prism::Router.new do
  get "/:who", KnockKnock
end

logger = Logger.new(STDOUT)
log_handler = Prism::LogHandler.new(logger)
handlers = [log_handler, router]

server = Prism::Server.new(handlers, logger)
server.bind_tcp(8000)
server.listen

#  INFO -- :   Prism::Server is listening on http://127.0.0.1:5000...
```
## Results in a error:
```bash
Error in src/simple_app.cr:4: Prism::Action is not a module, it's a struct

  include Prism::Action
```

## Crystal Info
```bash
$ crystal -v
Crystal 0.26.0 [eeb53c506] (2018-08-09)

LLVM: 4.0.0
Default target: x86_64-unknown-linux-gnu
```

**Comment by s0kil** [comment]
Seems to be related to https://github.com/vladfaust/prism/commit/d09b4f659aef9a93bb1cea8104081742cb97a54c

**Comment by vladfaust** [comment]
@DanielSokil use releases for stable versions. Master branch is considered to be the one with the lack of documentation.

**Comment by s0kil** [comment]
@vladfaust is version 0.3.0 not stable?

**Comment by vladfaust** [comment]
@DanielSokil v0.3.0 doesn't have https://github.com/vladfaust/prism/commit/d09b4f659aef9a93bb1cea8104081742cb97a54c included

**Comment by s0kil** [comment]
I have 0.3.0 installed, and getting this error.

**Comment by vladfaust** [comment]
@DanielSokil yes, sorry. Before  d09b4f6 `Prism::Action` is an abstract struct, and a module after. README is for master branch, which already has  d09b4f6 included.

**Comment by s0kil** [comment]
What can I do to resolve this error?

**Comment by vladfaust** [comment]
@DanielSokil see README at `v0.3.0` tag: https://github.com/vladfaust/prism/tree/v0.3.0

**Comment by vladfaust** [comment]
You may also use the edge release: https://github.com/vladfaust/prism/releases/tag/v0.4.0-beta.1

**Comment by s0kil** [comment]
Thanks!
