### ISSUE TITLE
Allow setting format for param errors

### ISSUE THREAD

**Issue by repomaa** [onyxframework/http#43]
For apis it would make sense to be able to handle the param erros manually so one can respond with json that can be parsed on the client side.

**Comment by vladfaust** [comment]
@jreinert sorry, but I don't understand the issue. Please provide an example.

**Comment by repomaa** [comment]
well if i make a request to a JSON API i've written using Prism, i'd expect to get back a JSON for any param errors occured for my request so i can parse the error in the client-facing frontend and display useful information, eg. highlight a form field and show the error under it.

**Comment by vladfaust** [comment]
You can reimplement [`Prism::Action::Params`](https://github.com/vladfaust/prism/blob/master/src/prism/action/params.cr) module (e.g. `MyParams`) and handle the errors manually, including `MyParams` instead `Prism::Action::Params` into your actions. BTW, Prism uses [callbacks.cr](https://github.com/vladfaust/callbacks.cr) under the hood.

**Comment by sandybrez** [comment]
They say I’m subscribed to you..I don’t recall doing this..
