### ISSUE TITLE
Cookies example

### ISSUE THREAD

**Issue by jackturnbull** [onyxframework/http#49]
I'm guessing there's a straightforward way of handling this but everything I end up with feels a little overcomplicated or sloppy, typically via `HTTP::Cookies` and the `Set-Cookie` header. Is there a nicer way of handling this?

Would this a good candidate for a documentation example? Or even some kind of helper module?

**Comment by vladfaust** [comment]
Hi, @jackturnbull,

I haven't used Prism with cookies before and, honestly, I never use them anywhere. I use Prism for pure JSON APIs with local storage and planning to continue working in this way. However, basically, you have an access to the context, so you can modify it as you want. You may grab an example from offical Crystal docs or even Kemal. Also you can offer an idea for `Prism::Action#cookie` method for easy cookie setting, but I'll need a working code snippet for that.

**Comment by vladfaust** [comment]
Reopen it if you have something to say.

**Comment by jackturnbull** [comment]
Sorry haven't been on my github this week - I'll give that a go. After a little research I ended up settling on [PASETO](https://paseto.io/) which I could quite happily generate from an endpoint and write it to local storage with JS if needed but I was hoping to have it as a cookie.

No harm though, I'll see if there's a natural place for them to fit!
