### ISSUE TITLE
Benchmark onyx vs FastHTTPRouter

### ISSUE THREAD

**Issue by proyb6** [onyxframework/http#54]
According to the latest benchmark, it appear to have a higher throughput than Onyx, it’s ideal to provide your own benchmark?

**Comment by vladfaust** [comment]
Still faster 🤔 

![image](https://user-images.githubusercontent.com/7955682/51715054-535f4f00-2048-11e9-8ca3-a6eae3f5a89e.png)

**Comment by proyb6** [comment]
It’s useful to test without Docker

**Comment by waghanza** [comment]
@proyb6 working on it https://github.com/the-benchmarker/web-frameworks/pull/632 :stuck_out_tongue: 

I think I'll have results for this at the end of the month

btw, I don't thin having `onyx` own benchmark is very accurate, it is one task to create a framework, and an other to compare it
