### ISSUE TITLE
Add session support ?

### ISSUE THREAD

**Issue by BlobCodes** [onyxframework/http#73]
I think a session handler like [kemal-session](https://github.com/kemalcr/kemal-session) or the session handler built into spider-gazelle's [action-controller](https://github.com/spider-gazelle/action-controller) would be a nice-to-have!

**Comment by vladfaust** [comment]
What is your use-case? If you want to save authenticated user, take a look at how it is implemented in [CrystalWorld](https://github.com/vladfaust/crystalworld/blob/master/src/endpoints/auth.cr). You can use modules to extend Endpoints with additional instance variables.

**Comment by BlobCodes** [comment]
That is exactly what I was searching!
I think this should be added to the docs.
Thank you!
