### ISSUE TITLE
Simplest hello world example crashes on crystal 0.27.2

### ISSUE THREAD

**Issue by epoch** [onyxframework/http#75]
works after upgrading crystal version to `0.28.0`

posting here to help others as I couldn't find anywhere in docs mentioning crystal version requirements.

```
in lib/onyx-http/src/onyx-http/middleware/renderer/rest_error.html.ecr:4: undefined constant ::HTTP::Status

  <title><%= error.is_a?(Error) ? error.status_message : ::HTTP::Status.new(500).description %></title>
```

**Comment by lebogan** [comment]
I got the same error using crystal `0.28.0` with LLVM 4.0.0 with Fedora 29 workstation. Closer inspection showed I was loading `0.7.4` onyx/http and `0.4.0` onyx. Changing http to `0.8.0` fixed my problem. Hope this helps.

**Comment by vladfaust** [comment]
I'll close it as we're on 0.29.0 already :smile:
